
// OVERALL OVERVIEW OF OBJECTS AND FLOW
//
// ATTRIBUTES
// ITEM STATS
// ITEM DATA
// ITEM
//
// RELATIONSHIP AS FOLLOWS
//
// ITEM - ITEM DATA - ITEM STATS (LIST) - ATTRIBUTES
//
//
// INVENTORY - ITEMS (LIST)
//
// ITEM UI
// INVENTORY CONTROLLER - ITEM UI (LIST)
